
---
apiVersion: v1
data:
    vcap-properties.yaml: dmNhcC5hcHBsaWNhdGlvbi5hcHBsaWNhdGlvbl92ZXJzaW9uOiA1M2MyZGZkNC1hMmQ5LTQ2ZWUtYmZhNi1hZmI0YzgxNTU3MjQKdmNhcC5hcHBsaWNhdGlvbi5uYW1lOiBnYXRld2F5CnZjYXAuYXBwbGljYXRpb24udXNlcnM6IAp2Y2FwLmFwcGxpY2F0aW9uLmFwcGxpY2F0aW9uX2lkOiA0NGE0NThjNC1kZWEwLTQyNWItODlhYy1hYjk1ZDlkMTJhZjcKdmNhcC5hcHBsaWNhdGlvbi5hcHBsaWNhdGlvbl9uYW1lOiBnYXRld2F5CnZjYXAuYXBwbGljYXRpb24uYXBwbGljYXRpb25fdXJpczogZW50ZXJwcmlzZS1hcHAtNTI1MjEwODM5LWdhdGV3YXkuMjAuMjMxLjEyMS4xODQubmlwLmlvCnZjYXAuYXBwbGljYXRpb24uYXBwbGljYXRpb25fdXJpc1swXTogZW50ZXJwcmlzZS1hcHAtNTI1MjEwODM5LWdhdGV3YXkuMjAuMjMxLjEyMS4xODQubmlwLmlvCnZjYXAuYXBwbGljYXRpb24uc3BhY2VfbmFtZTogZW50ZXJwcmlzZQp2Y2FwLmFwcGxpY2F0aW9uLnVyaXM6IGVudGVycHJpc2UtYXBwLTUyNTIxMDgzOS1nYXRld2F5LjIwLjIzMS4xMjEuMTg0Lm5pcC5pbwp2Y2FwLmFwcGxpY2F0aW9uLnVyaXNbMF06IGVudGVycHJpc2UtYXBwLTUyNTIxMDgzOS1nYXRld2F5LjIwLjIzMS4xMjEuMTg0Lm5pcC5pbwp2Y2FwLmFwcGxpY2F0aW9uLnZlcnNpb246IDUzYzJkZmQ0LWEyZDktNDZlZS1iZmE2LWFmYjRjODE1NTcyNAp2Y2FwLmFwcGxpY2F0aW9uLmNmX2FwaTogaHR0cHM6Ly9hcGkuMjAuMjMxLjEyMS4xODQubmlwLmlvCnZjYXAuYXBwbGljYXRpb24ubGltaXRzLmRpc2s6IDEwMjQKdmNhcC5hcHBsaWNhdGlvbi5saW1pdHMuZmRzOiAxNjM4NAp2Y2FwLmFwcGxpY2F0aW9uLmxpbWl0cy5tZW06IDEwMjQKdmNhcC5hcHBsaWNhdGlvbi5zcGFjZV9pZDogMzAyZmZlMGMtMzgzZC00NGNhLTg3MmItYWY3N2JjNTlmNjNm
kind: Secret
metadata:
    creationTimestamp: null
    name: gateway-vcapasspringbootproperties
type: Opaque

...
