apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: m2kdemo1-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: m2kdemo1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy/yamls
    repoURL: https://github.com/Jobinl400EY/m2kdemo1
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
