
---
apiVersion: v1
data:
    vcap-properties.yaml: dmNhcC5hcHBsaWNhdGlvbi51c2VyczogCnZjYXAuYXBwbGljYXRpb24uYXBwbGljYXRpb25fbmFtZTogb3JkZXJzCnZjYXAuYXBwbGljYXRpb24uY2ZfYXBpOiBodHRwczovL2FwaS4yMC4yMzEuMTIxLjE4NC5uaXAuaW8KdmNhcC5hcHBsaWNhdGlvbi5uYW1lOiBvcmRlcnMKdmNhcC5hcHBsaWNhdGlvbi5zcGFjZV9uYW1lOiBlbnRlcnByaXNlCnZjYXAuYXBwbGljYXRpb24uc3BhY2VfaWQ6IDMwMmZmZTBjLTM4M2QtNDRjYS04NzJiLWFmNzdiYzU5ZjYzZgp2Y2FwLmFwcGxpY2F0aW9uLnVyaXM6IGVudGVycHJpc2UtYXBwLTUyNTIxMDgzOS1vcmRlcnMuMjAuMjMxLjEyMS4xODQubmlwLmlvCnZjYXAuYXBwbGljYXRpb24udXJpc1swXTogZW50ZXJwcmlzZS1hcHAtNTI1MjEwODM5LW9yZGVycy4yMC4yMzEuMTIxLjE4NC5uaXAuaW8KdmNhcC5hcHBsaWNhdGlvbi52ZXJzaW9uOiA3ODg0YTEyMC0wNDBhLTQ0NGMtYmFmMi1iODhkNTg4OGQ3MjcKdmNhcC5hcHBsaWNhdGlvbi5hcHBsaWNhdGlvbl9pZDogMTcyZDYwZTUtZmE0MS00NTVhLWI3ZDMtMGE5MGU3YThhNDNkCnZjYXAuYXBwbGljYXRpb24uYXBwbGljYXRpb25fdXJpczogZW50ZXJwcmlzZS1hcHAtNTI1MjEwODM5LW9yZGVycy4yMC4yMzEuMTIxLjE4NC5uaXAuaW8KdmNhcC5hcHBsaWNhdGlvbi5hcHBsaWNhdGlvbl91cmlzWzBdOiBlbnRlcnByaXNlLWFwcC01MjUyMTA4Mzktb3JkZXJzLjIwLjIzMS4xMjEuMTg0Lm5pcC5pbwp2Y2FwLmFwcGxpY2F0aW9uLmFwcGxpY2F0aW9uX3ZlcnNpb246IDc4ODRhMTIwLTA0MGEtNDQ0Yy1iYWYyLWI4OGQ1ODg4ZDcyNwp2Y2FwLmFwcGxpY2F0aW9uLmxpbWl0cy5mZHM6IDE2Mzg0CnZjYXAuYXBwbGljYXRpb24ubGltaXRzLm1lbTogMTAyNAp2Y2FwLmFwcGxpY2F0aW9uLmxpbWl0cy5kaXNrOiAxMDI0
kind: Secret
metadata:
    creationTimestamp: null
    name: orders-vcapasspringbootproperties
type: Opaque

...
